
/**
 * Initially generated by Mod4j at Sat Mar 07 22:20:49 CET 2009
 */
package org.company.webshop.data.hibernate.spring;

import org.company.webshop.data.DerivedDao;
import org.company.webshop.data.hibernate.spring.DerivedDaoImplBase;

/**
 * Derived Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Derived objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class DerivedDaoImpl extends DerivedDaoImplBase implements DerivedDao {

}
