/**
 * Initially generated by Mod4j at Thu Feb 26 16:47:48 CET 2009
 */
package org.company.webshop.data.hibernate.spring;

import org.company.webshop.data.Many2ManyOrderedToDao;
import org.company.webshop.data.hibernate.spring.Many2ManyOrderedToDaoImplBase;

/**
 * Many2ManyOrderedTo Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Many2ManyOrderedTo objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class Many2ManyOrderedToDaoImpl extends Many2ManyOrderedToDaoImplBase
		implements
			Many2ManyOrderedToDao {

}
