/**
 * Initially generated by Mod4j at Thu Feb 26 16:47:48 CET 2009
 */
package org.company.webshop.data.hibernate.spring;

import org.company.webshop.data.One2ManyOrderedToDao;
import org.company.webshop.data.hibernate.spring.One2ManyOrderedToDaoImplBase;

/**
 * One2ManyOrderedTo Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting One2ManyOrderedTo objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class One2ManyOrderedToDaoImpl extends One2ManyOrderedToDaoImplBase
		implements
			One2ManyOrderedToDao {

}
