/**
 * Initially generated by Mod4j at Thu Feb 26 16:47:50 CET 2009
 */
package org.company.webshop.data.hibernate.spring;

import org.company.webshop.data.OrderDao;
import org.company.webshop.data.OrderLineDao;
import org.company.webshop.data.hibernate.spring.OrderDaoImplBase;
import org.company.webshop.domain.Order;
import org.company.webshop.domain.OrderLine;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * Order Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Order objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class OrderDaoImpl extends OrderDaoImplBase implements OrderDao {

    @Autowired
    private OrderLineDao orderlineDao;
    
    /** 
     * Workaround for a cascading delete of all orderlines attached the order to delete.
     * @see org.company.webshop.data.hibernate.spring.OrderDaoImplBase#delete(org.company.webshop.domain.Order)
     */
    @Override
    public void delete(Order object) {
        
        
        for (OrderLine line: object.getOrderLines()){
            orderlineDao.delete(line);
        }
        super.delete(object);
    }
    
    
}
