
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:43 CEST 2010
 *     Application model: Relation
 *     Generator        :  Mod4j BusinessDomainDsl generator: DaoImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.webshop.data.hibernate.spring;

import org.company.webshop.data.RelationDao;
import org.company.webshop.data.hibernate.spring.RelationDaoImplBase;

/**
 * Relation Data Access Object (DAO) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Relation objects in the database.
 * All database access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class RelationDaoImpl extends RelationDaoImplBase implements RelationDao {

}
