
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:37 CEST 2010
 *     Application model: Subclass
 *     Generator        :  Mod4j BusinessDomainDsl generator: DaoImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.webshop.data.hibernate.spring;

import org.company.webshop.data.SubclassDao;
import org.company.webshop.data.hibernate.spring.SubclassDaoImplBase;

/**
 * Subclass Data Access Object (DAO) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Subclass objects in the database.
 * All database access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class SubclassDaoImpl extends SubclassDaoImplBase implements SubclassDao {

}
