
/**
 * Initially generated by Mod4j Service DSL: LocalServiceImpl::LocalServiceImpl at: Sun Mar 08 15:44:41 CET 2009
 * from model TestSVC
 * Extension point: intended to be changed by hand.
 */
package org.company.recordshop.service;

import java.util.List;

import org.company.recordshop.business.TestSVCDomainService;
import org.company.recordshop.service.TestSVCLocalServiceImplBase;
import org.company.recordshop.service.dto.DerivedDto;

import org.company.recordshop.service.dto.translators.DerivedDtoTranslator;
import org.company.recordshop.domain.Derived;

/**
 * @author Initially generated by Mod4j
 */
public class TestSVCLocalServiceImpl extends TestSVCLocalServiceImplBase {

}
