
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:38 CEST 2010
 *     Application model: Records
 *     Generator        :  Mod4j ServiceDsl generator: LocalServiceImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.webshop.service;

import org.company.webshop.service.RecordsLocalServiceImplBase;


/**
 * @author Initially generated by Mod4j
 */
public class RecordsLocalServiceImpl extends RecordsLocalServiceImplBase {

}
