
/**
 * Initially generated by Mod4j Service DSL: LocalServiceImpl::LocalServiceImpl at: Sun Mar 08 15:44:41 CET 2009
 * from model TestSVC
 * Extension point: intended to be changed by hand.
 */
package org.company.webshop.service;

import org.company.webshop.service.TestSVCLocalServiceImplBase;


/**
 * @author Initially generated by Mod4j
 */
public class TestSVCLocalServiceImpl extends TestSVCLocalServiceImplBase {

}
