
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: CasusOverlegDto
 *     Generator        : Mod4j DataContractDsl generator: dtoBean.xpt
 */

package org.company.webshop.service.dto;

import org.joda.time.DateTime;
import org.mod4j.runtime.dto.AbstractDto;

/**
 * 
 *
 * @author generated by Mod4j
 */
public class CasusOverlegDto extends AbstractDto {

	/**
	 *  naam: 
	 */

	private String naam;

	/**
	 *  datum: 
	 */

	private DateTime datum;

	/**
	 * Default no-argument constructor.
	 */
	public CasusOverlegDto() {
		super();
	}

	/**
	 * Constructor for use by the DTO Translator.
	 * 
	 * @param id
	 *            The ID of the referenced business object.
	 * @param version
	 *            The version of the referenced business object.
	 */
	public CasusOverlegDto(final Long id, final Integer version) {
		super(id, version);
	}

	/**
	 * @param naam (String) 
	 */
	public void setNaam(final String naam) {
		this.naam = naam;
	}

	/**
	 *
	 * @return naam (String) 
	 */
	public String getNaam() {
		return this.naam;
	}

	/**
	 * @param datum (DateTime) 
	 */
	public void setDatum(final DateTime datum) {
		this.datum = datum;
	}

	/**
	 *
	 * @return datum (DateTime) 
	 */
	public DateTime getDatum() {
		return this.datum;
	}

	/**
	 * Sets all attributes that have a default value, to their default values.
	 *
	 * @author Generated by Mod4j
	 */
	public void clear() {
		naam = null;
		datum = null;

	}

	/**
	 * toString method for CasusOverlegDto
	 */
	@Override
	public String toString() {
		StringBuffer result = new StringBuffer();
		result.append("org.company.webshop.service.dto.CasusOverlegDto[");
		result.append("id=");
		result.append(getId());
		result.append(",");
		result.append("version=");
		result.append(getVersion());

		result.append(",");
		result.append("naam=");
		result.append(naam);

		result.append(",");
		result.append("datum=");
		result.append(datum);

		result.append("]");
		return result.toString();
	}

}
