
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: sexeEnumDto
 *     Generator        : Mod4j DatcontractDsl generator: Enumeration.xpt
 */

package org.company.webshop.service.dto;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

/**
 * 
 *
 * Generated at: Fri Jun 10 13:47:12 CEST 2011
 */
public enum SexeEnumDto {

	FEMALE(2), MALE(3);

	private static final Map<Integer, SexeEnumDto> lookup = new HashMap<Integer, SexeEnumDto>();
	static {
		for (SexeEnumDto s : EnumSet.allOf(SexeEnumDto.class))
			lookup.put(s.id(), s);
	}

	private Integer id;

	private SexeEnumDto(Integer id) {
		this.id = id;
	}

	public Integer id() {
		return id;
	}

	public static SexeEnumDto value(Integer id) {
		return lookup.get(id);
	}
}
