
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: Empty
 *     Generator        : Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 */

package org.company.webshop.domain;

import org.company.webshop.domain.Empty;

/**
 * A subclass of Empty to be used as example object
 * in Query-by-Example (QBE) queries. It turns off validation in the
 * no-argument constructor.
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public final class EmptyExample extends Empty {

	/**
	 * Minimal public constructor
	 */
	public EmptyExample() {
		activateValidation(false);
	}
}
