
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:09 CEST 2011
 *     Application model: OrderLine
 *     Generator        : Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 */

package org.company.webshop.domain;

import org.company.webshop.domain.OrderLine;

/**
 * A subclass of OrderLine to be used as example object
 * in Query-by-Example (QBE) queries. It turns off validation in the
 * no-argument constructor.
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public final class OrderLineExample extends OrderLine {

	/**
	 * Minimal public constructor
	 */
	public OrderLineExample() {
		activateValidation(false);
		quantity = null;
	}
}
