
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: Subclass3
 *     Generator        : Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 */

package org.company.webshop.domain;

import org.company.webshop.domain.Subclass;
import org.company.webshop.domain.Subclass3;
import org.mod4j.runtime.validation.NotNullValidator;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
@SuppressWarnings("serial")
public abstract class Subclass3ImplBase extends Subclass
		implements
			java.io.Serializable {

	/**
	 * toString method for Subclass3ImplBase
	 */
	@Override
	public String toString() {
		StringBuffer result = new StringBuffer();
		result.append("org.company.webshop.domain.Subclass3[");
		result.append("id=");
		result.append(getId());
		result.append(",");
		result.append("version=");
		result.append(getVersion());

		result.append(",");
		result.append("name=");
		result.append(name);

		result.append(",");
		result.append("active=");
		result.append(active);

		result.append(",");
		result.append("dummy=");
		result.append(dummy);

		result.append("]");
		return result.toString();
	}

	/**
	 *  dummy: 
	 */
	protected String dummy;

	private void addValidators() {

		validation.addValidator(new NotNullValidator(Subclass3.class, "dummy"));

	}

	/**
	 * Default no-argument constructor for Subclass3ImplBase 
	 */
	protected Subclass3ImplBase() {
		super();
		addValidators();
	}

	/**
	 * Minimal constructor for Subclass3ImplBase
	 *
	 * @param name (String) 
	 * @param dummy (String) 
	 */
	public Subclass3ImplBase(String name, String dummy) {
		super(name);

		this.dummy = dummy;
		addValidators();
		validation.validate();
	}

	/**
	 * @return dummy (String) 
	 */
	public String getDummy() {
		return this.dummy;
	}

	/**
	 * @param dummy (String) 
	 */
	public void setDummy(final String dummy) {
		this.dummy = dummy;
		validation.validate();
	}

	/**
	 * Activate/deactivate validation for this business class.
	 * When set to active the validation will immediately be executed.
	 * 
	 * @param value (boolean) 
	 */
	public void activateValidation(boolean value) {

		this.validation.setActive(value);
		if (value) {
			validation.validate();
		}
	}

}
