
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: Subclass3
 *     Generator        : Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 */

package org.company.webshop.domain;

import org.company.webshop.domain.Subclass3;

/**
 * A subclass of Subclass3 to be used as example object
 * in Query-by-Example (QBE) queries. It turns off validation in the
 * no-argument constructor.
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public final class Subclass3Example extends Subclass3 {

	/**
	 * Minimal public constructor
	 */
	public Subclass3Example() {
		activateValidation(false);
		active = null;
	}
}
