/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: Empty2
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.webshop.data;

import java.util.List;

import org.company.webshop.domain.Empty2;
import org.company.webshop.domain.Empty2Example;

/**
 * Empty2DaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface Empty2DaoBase {

	/**
	 * Retrieves a Empty2 by its ID from the database.
	 * 
	 * @param id id of the Empty2 to retrieve.
	 * @return Empty2 retrieved or null when no Empty2 was found.
	 */
	Empty2 retrieve(Long id);

	/**
	 * Adds a new Empty2 to the database
	 * 
	 * @param object
	 *                the Empty2 to add to the database.
	 * @return the stored Empty2.
	 */
	Long add(Empty2 object);

	/**
	 * Deletes a Empty2 from the database.
	 * 
	 * @param object
	 *                the Empty2 to delete
	 */
	void delete(Empty2 object);

	/**
	 * Selects all Empty2s from the database.
	 * 
	 * @return a List of all Empty2 objects.
	 */
	List<Empty2> listAll();

	/**
	 * Selects a range (page) of Empty2s from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more Empty2 objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<Empty2> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of Empty2s from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Empty2 objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Empty2> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of Empty2s from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Empty2 objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Empty2> listPageByExample(final Empty2Example example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted Empty2 objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted Empty2 objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final Empty2Example example);

	/**
	 * Selects Empty2s from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of Empty2 objects.
	 */
	List<Empty2> findByExample(Empty2Example example);
}
