/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:11 CEST 2011
 *     Application model: Many2ManyTo
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.webshop.data;

import java.util.List;

import org.company.webshop.domain.Many2ManyTo;
import org.company.webshop.domain.Many2ManyToExample;

/**
 * Many2ManyToDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface Many2ManyToDaoBase {

	/**
	 * Retrieves a Many2ManyTo by its ID from the database.
	 * 
	 * @param id id of the Many2ManyTo to retrieve.
	 * @return Many2ManyTo retrieved or null when no Many2ManyTo was found.
	 */
	Many2ManyTo retrieve(Long id);

	/**
	 * Adds a new Many2ManyTo to the database
	 * 
	 * @param object
	 *                the Many2ManyTo to add to the database.
	 * @return the stored Many2ManyTo.
	 */
	Long add(Many2ManyTo object);

	/**
	 * Deletes a Many2ManyTo from the database.
	 * 
	 * @param object
	 *                the Many2ManyTo to delete
	 */
	void delete(Many2ManyTo object);

	/**
	 * Selects all Many2ManyTos from the database.
	 * 
	 * @return a List of all Many2ManyTo objects.
	 */
	List<Many2ManyTo> listAll();

	/**
	 * Selects a range (page) of Many2ManyTos from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more Many2ManyTo objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<Many2ManyTo> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of Many2ManyTos from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Many2ManyTo objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Many2ManyTo> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of Many2ManyTos from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Many2ManyTo objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Many2ManyTo> listPageByExample(final Many2ManyToExample example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted Many2ManyTo objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted Many2ManyTo objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final Many2ManyToExample example);

	/**
	 * Selects Many2ManyTos from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of Many2ManyTo objects.
	 */
	List<Many2ManyTo> findByExample(Many2ManyToExample example);
}
