/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:11 CEST 2011
 *     Application model: MyDerived
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.webshop.data;

import java.util.List;

import org.company.webshop.domain.MyDerived;
import org.company.webshop.domain.MyDerivedExample;

/**
 * MyDerivedDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface MyDerivedDaoBase {

	/**
	 * Retrieves a MyDerived by its ID from the database.
	 * 
	 * @param id id of the MyDerived to retrieve.
	 * @return MyDerived retrieved or null when no MyDerived was found.
	 */
	MyDerived retrieve(Long id);

	/**
	 * Adds a new MyDerived to the database
	 * 
	 * @param object
	 *                the MyDerived to add to the database.
	 * @return the stored MyDerived.
	 */
	Long add(MyDerived object);

	/**
	 * Deletes a MyDerived from the database.
	 * 
	 * @param object
	 *                the MyDerived to delete
	 */
	void delete(MyDerived object);

	/**
	 * Selects all MyDeriveds from the database.
	 * 
	 * @return a List of all MyDerived objects.
	 */
	List<MyDerived> listAll();

	/**
	 * Selects a range (page) of MyDeriveds from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more MyDerived objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<MyDerived> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of MyDeriveds from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more MyDerived objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<MyDerived> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of MyDeriveds from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more MyDerived objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<MyDerived> listPageByExample(final MyDerivedExample example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted MyDerived objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted MyDerived objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final MyDerivedExample example);

	/**
	 * Selects MyDeriveds from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of MyDerived objects.
	 */
	List<MyDerived> findByExample(MyDerivedExample example);
}
