/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:11 CEST 2011
 *     Application model: One2ManyOrderedTo
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.webshop.data;

import java.util.List;

import org.company.webshop.domain.One2ManyOrderedTo;
import org.company.webshop.domain.One2ManyOrderedToExample;

/**
 * One2ManyOrderedToDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface One2ManyOrderedToDaoBase {

	/**
	 * Retrieves a One2ManyOrderedTo by its ID from the database.
	 * 
	 * @param id id of the One2ManyOrderedTo to retrieve.
	 * @return One2ManyOrderedTo retrieved or null when no One2ManyOrderedTo was found.
	 */
	One2ManyOrderedTo retrieve(Long id);

	/**
	 * Adds a new One2ManyOrderedTo to the database
	 * 
	 * @param object
	 *                the One2ManyOrderedTo to add to the database.
	 * @return the stored One2ManyOrderedTo.
	 */
	Long add(One2ManyOrderedTo object);

	/**
	 * Deletes a One2ManyOrderedTo from the database.
	 * 
	 * @param object
	 *                the One2ManyOrderedTo to delete
	 */
	void delete(One2ManyOrderedTo object);

	/**
	 * Selects all One2ManyOrderedTos from the database.
	 * 
	 * @return a List of all One2ManyOrderedTo objects.
	 */
	List<One2ManyOrderedTo> listAll();

	/**
	 * Selects a range (page) of One2ManyOrderedTos from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more One2ManyOrderedTo objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<One2ManyOrderedTo> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of One2ManyOrderedTos from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more One2ManyOrderedTo objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<One2ManyOrderedTo> listPage(final int firstResult,
			final int maxResults, final String sortProperty,
			final boolean isAscending);

	/**
	 * Selects a sorted range (page) of One2ManyOrderedTos from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more One2ManyOrderedTo objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<One2ManyOrderedTo> listPageByExample(
			final One2ManyOrderedToExample example, final int firstResult,
			final int maxResults, final String sortProperty,
			final boolean isAscending);

	/**
	 * Counts the number of persisted One2ManyOrderedTo objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted One2ManyOrderedTo objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final One2ManyOrderedToExample example);

	/**
	 * Selects One2ManyOrderedTos from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of One2ManyOrderedTo objects.
	 */
	List<One2ManyOrderedTo> findByExample(One2ManyOrderedToExample example);
}
