/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: OrderLine
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.webshop.data;

import java.util.List;

import org.company.webshop.domain.OrderLine;
import org.company.webshop.domain.OrderLineExample;

/**
 * OrderLineDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface OrderLineDaoBase {

	/**
	 * Retrieves a OrderLine by its ID from the database.
	 * 
	 * @param id id of the OrderLine to retrieve.
	 * @return OrderLine retrieved or null when no OrderLine was found.
	 */
	OrderLine retrieve(Long id);

	/**
	 * Adds a new OrderLine to the database
	 * 
	 * @param object
	 *                the OrderLine to add to the database.
	 * @return the stored OrderLine.
	 */
	Long add(OrderLine object);

	/**
	 * Deletes a OrderLine from the database.
	 * 
	 * @param object
	 *                the OrderLine to delete
	 */
	void delete(OrderLine object);

	/**
	 * Selects all OrderLines from the database.
	 * 
	 * @return a List of all OrderLine objects.
	 */
	List<OrderLine> listAll();

	/**
	 * Selects a range (page) of OrderLines from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more OrderLine objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<OrderLine> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of OrderLines from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more OrderLine objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<OrderLine> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of OrderLines from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more OrderLine objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<OrderLine> listPageByExample(final OrderLineExample example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted OrderLine objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted OrderLine objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final OrderLineExample example);

	/**
	 * Selects OrderLines from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of OrderLine objects.
	 */
	List<OrderLine> findByExample(OrderLineExample example);
}
