/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: Subclass2
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.webshop.data;

import java.util.List;

import org.company.webshop.domain.Subclass2;
import org.company.webshop.domain.Subclass2Example;

/**
 * Subclass2DaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface Subclass2DaoBase {

	/**
	 * Retrieves a Subclass2 by its ID from the database.
	 * 
	 * @param id id of the Subclass2 to retrieve.
	 * @return Subclass2 retrieved or null when no Subclass2 was found.
	 */
	Subclass2 retrieve(Long id);

	/**
	 * Adds a new Subclass2 to the database
	 * 
	 * @param object
	 *                the Subclass2 to add to the database.
	 * @return the stored Subclass2.
	 */
	Long add(Subclass2 object);

	/**
	 * Deletes a Subclass2 from the database.
	 * 
	 * @param object
	 *                the Subclass2 to delete
	 */
	void delete(Subclass2 object);

	/**
	 * Selects all Subclass2s from the database.
	 * 
	 * @return a List of all Subclass2 objects.
	 */
	List<Subclass2> listAll();

	/**
	 * Selects a range (page) of Subclass2s from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more Subclass2 objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<Subclass2> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of Subclass2s from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Subclass2 objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Subclass2> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of Subclass2s from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Subclass2 objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Subclass2> listPageByExample(final Subclass2Example example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted Subclass2 objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted Subclass2 objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final Subclass2Example example);

	/**
	 * Selects Subclass2s from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of Subclass2 objects.
	 */
	List<Subclass2> findByExample(Subclass2Example example);
}
