
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: AgedPerson
 *     Generator        : Mod4j DataContractDsl generator: dtoBean.xpt
 */

package org.company.recordshop.service.dto;

import org.mod4j.runtime.dto.AbstractDto;

/**
 * 
 *
 * @author generated by Mod4j
 */
public class AgedPerson extends AbstractDto {

	/**
	 *  firstName: 
	 */

	private String firstName;

	/**
	 *  lastName: 
	 */

	private String lastName;

	/**
	 *  age: 
	 */

	private Integer age;

	/**
	 * Default no-argument constructor.
	 */
	public AgedPerson() {
		super();
	}

	/**
	 * Constructor for use by the DTO Translator.
	 * 
	 * @param id
	 *            The ID of the referenced business object.
	 * @param version
	 *            The version of the referenced business object.
	 */
	public AgedPerson(final Long id, final Integer version) {
		super(id, version);
	}

	/**
	 * @param firstName (String) 
	 */
	public void setFirstName(final String firstName) {
		this.firstName = firstName;
	}

	/**
	 *
	 * @return firstName (String) 
	 */
	public String getFirstName() {
		return this.firstName;
	}

	/**
	 * @param lastName (String) 
	 */
	public void setLastName(final String lastName) {
		this.lastName = lastName;
	}

	/**
	 *
	 * @return lastName (String) 
	 */
	public String getLastName() {
		return this.lastName;
	}

	/**
	 * @param age (Integer) 
	 */
	public void setAge(final Integer age) {
		this.age = age;
	}

	/**
	 *
	 * @return age (Integer) 
	 */
	public Integer getAge() {
		return this.age;
	}

	/**
	 * Sets all attributes that have a default value, to their default values.
	 *
	 * @author Generated by Mod4j
	 */
	public void clear() {
		firstName = null;
		lastName = null;
		age = null;

	}

	/**
	 * toString method for AgedPerson
	 */
	@Override
	public String toString() {
		StringBuffer result = new StringBuffer();
		result.append("org.company.recordshop.service.dto.AgedPerson[");
		result.append("id=");
		result.append(getId());
		result.append(",");
		result.append("version=");
		result.append(getVersion());

		result.append(",");
		result.append("firstName=");
		result.append(firstName);

		result.append(",");
		result.append("lastName=");
		result.append(lastName);

		result.append(",");
		result.append("age=");
		result.append(age);

		result.append("]");
		return result.toString();
	}

}
