
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: DateDto
 *     Generator        : Mod4j BusinessDomainDsl generator: dtoBean.xpt
 */

package org.company.recordshop.service.dto;

import java.io.Serializable;

import org.joda.time.DateTime;

/**
 * Date transfer object.
 *
 * @author Generated by Mod4j
 */
@SuppressWarnings("serial")
public class DateDto implements Serializable {

	/**
	 *  date: date
	 */

	private DateTime date;

	/**
	 * Default no-argument constructor.
	 */
	public DateDto() {
		super();
	}

	/**
	 *
	 * @return date (DateTime) date
	 */
	public DateTime getDate() {
		return this.date;
	}

	/**
	 * @param date (DateTime) date
	 */
	public void setDate(final DateTime date) {
		this.date = date;
	}

}
