
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:13 CEST 2011
 *     Application model: DerivedDto
 *     Generator        : Mod4j DataContractDsl generator: dtoBean.xpt
 */

package org.company.recordshop.service.dto;

import org.mod4j.runtime.dto.AbstractDto;

import org.joda.time.DateTime;

/**
 * 
 *
 * @author generated by Mod4j
 */
public class DerivedDto extends AbstractDto {

	/**
	 *  first: 
	 */

	private String first;

	/**
	 *  secondo: 
	 */

	private Boolean secondo;

	/**
	 *  third: 
	 */

	private DateTime third;

	/**
	 *  fourth: 
	 */

	private Integer fourth;

	/**
	 *  fifth: 
	 */

	private Float fifth;

	/**
	 * Default no-argument constructor.
	 */
	public DerivedDto() {
		super();
	}

	/**
	 * Constructor for use by the DTO Translator.
	 * 
	 * @param id
	 *            The ID of the referenced business object.
	 * @param version
	 *            The version of the referenced business object.
	 */
	public DerivedDto(final Long id, final Integer version) {
		super(id, version);
	}

	/**
	 * @param first (String) 
	 */
	public void setFirst(final String first) {
		this.first = first;
	}

	/**
	 *
	 * @return first (String) 
	 */
	public String getFirst() {
		return this.first;
	}

	/**
	 * @param secondo (Boolean) 
	 */
	public void setSecondo(final Boolean secondo) {
		this.secondo = secondo;
	}

	/**
	 *
	 * @return secondo (Boolean) 
	 */
	public Boolean isSecondo() {
		return this.secondo;
	}

	/**
	 * @param third (DateTime) 
	 */
	public void setThird(final DateTime third) {
		this.third = third;
	}

	/**
	 *
	 * @return third (DateTime) 
	 */
	public DateTime getThird() {
		return this.third;
	}

	/**
	 * @param fourth (Integer) 
	 */
	public void setFourth(final Integer fourth) {
		this.fourth = fourth;
	}

	/**
	 *
	 * @return fourth (Integer) 
	 */
	public Integer getFourth() {
		return this.fourth;
	}

	/**
	 * @param fifth (Float) 
	 */
	public void setFifth(final Float fifth) {
		this.fifth = fifth;
	}

	/**
	 *
	 * @return fifth (Float) 
	 */
	public Float getFifth() {
		return this.fifth;
	}

	/**
	 * Sets all attributes that have a default value, to their default values.
	 *
	 * @author Generated by Mod4j
	 */
	public void clear() {
		first = null;
		secondo = null;
		third = null;
		fourth = null;
		fifth = null;

	}

	/**
	 * toString method for DerivedDto
	 */
	@Override
	public String toString() {
		StringBuffer result = new StringBuffer();
		result.append("org.company.recordshop.service.dto.DerivedDto[");
		result.append("id=");
		result.append(getId());
		result.append(",");
		result.append("version=");
		result.append(getVersion());

		result.append(",");
		result.append("first=");
		result.append(first);

		result.append(",");
		result.append("secondo=");
		result.append(secondo);

		result.append(",");
		result.append("third=");
		result.append(third);

		result.append(",");
		result.append("fourth=");
		result.append(fourth);

		result.append(",");
		result.append("fifth=");
		result.append(fifth);

		result.append("]");
		return result.toString();
	}

}
