
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: FullRecordDto
 *     Generator        : Mod4j DataContractDsl generator: dtoBean.xpt
 */

package org.company.recordshop.service.dto;

import org.mod4j.runtime.dto.AbstractDto;

/**
 * 
 *
 * @author generated by Mod4j
 */
public class FullRecordDto extends AbstractDto {

	/**
	 *  asin: 
	 */

	private String asin;

	/**
	 *  title: 
	 */

	private String title = "Title unknown";

	/**
	 *  mediumCode: 
	 */

	private Integer mediumCode = 111;

	/**
	 *  price: 
	 */

	private Float price;

	/**
	 *  type: 
	 */

	private RecordTypeEnumDto type;

	/**
	 * Default no-argument constructor.
	 */
	public FullRecordDto() {
		super();
	}

	/**
	 * Constructor for use by the DTO Translator.
	 * 
	 * @param id
	 *            The ID of the referenced business object.
	 * @param version
	 *            The version of the referenced business object.
	 */
	public FullRecordDto(final Long id, final Integer version) {
		super(id, version);
	}

	/**
	 * @param asin (String) 
	 */
	public void setAsin(final String asin) {
		this.asin = asin;
	}

	/**
	 *
	 * @return asin (String) 
	 */
	public String getAsin() {
		return this.asin;
	}

	/**
	 * @param title (String) 
	 */
	public void setTitle(final String title) {
		this.title = title;
	}

	/**
	 *
	 * @return title (String) 
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * @param mediumCode (Integer) 
	 */
	public void setMediumCode(final Integer mediumCode) {
		this.mediumCode = mediumCode;
	}

	/**
	 *
	 * @return mediumCode (Integer) 
	 */
	public Integer getMediumCode() {
		return this.mediumCode;
	}

	/**
	 * @param price (Float) 
	 */
	public void setPrice(final Float price) {
		this.price = price;
	}

	/**
	 *
	 * @return price (Float) 
	 */
	public Float getPrice() {
		return this.price;
	}

	/**
	 * @param type (RecordTypeEnumDto) 
	 */
	public void setType(final RecordTypeEnumDto type) {
		this.type = type;
	}

	/**
	 *
	 * @return type (RecordTypeEnumDto) 
	 */
	public RecordTypeEnumDto getType() {
		return this.type;
	}

	/**
	 * Sets all attributes that have a default value, to their default values.
	 *
	 * @author Generated by Mod4j
	 */
	public void clear() {
		asin = null;
		title = null;
		mediumCode = null;
		price = null;
		type = null;

	}

	/**
	 * toString method for FullRecordDto
	 */
	@Override
	public String toString() {
		StringBuffer result = new StringBuffer();
		result.append("org.company.recordshop.service.dto.FullRecordDto[");
		result.append("id=");
		result.append(getId());
		result.append(",");
		result.append("version=");
		result.append(getVersion());

		result.append(",");
		result.append("asin=");
		result.append(asin);

		result.append(",");
		result.append("title=");
		result.append(title);

		result.append(",");
		result.append("mediumCode=");
		result.append(mediumCode);

		result.append(",");
		result.append("price=");
		result.append(price);

		result.append(",");
		result.append("type=");
		result.append(type);

		result.append("]");
		return result.toString();
	}

}
