
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: lowerRecordTypeEnumDto
 *     Generator        : Mod4j DatcontractDsl generator: Enumeration.xpt
 */

package org.company.recordshop.service.dto;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

/**
 * 
 *
 * Generated at: Fri Jun 10 13:47:12 CEST 2011
 */
public enum LowerRecordTypeEnumDto {

	LP(2), CD(3), DVD(4), BLUERAY(5);

	private static final Map<Integer, LowerRecordTypeEnumDto> lookup = new HashMap<Integer, LowerRecordTypeEnumDto>();
	static {
		for (LowerRecordTypeEnumDto s : EnumSet
				.allOf(LowerRecordTypeEnumDto.class))
			lookup.put(s.id(), s);
	}

	private Integer id;

	private LowerRecordTypeEnumDto(Integer id) {
		this.id = id;
	}

	public Integer id() {
		return id;
	}

	public static LowerRecordTypeEnumDto value(Integer id) {
		return lookup.get(id);
	}
}
