
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: OrderlineWithRecordRefsDto
 *     Generator        : Mod4j DataContractDsl generator: dtoBean.xpt
 */

package org.company.recordshop.service.dto;

import org.mod4j.runtime.dto.AbstractDto;

/**
 * 
 *
 * @author generated by Mod4j
 */
public class OrderlineWithRecordRefsDto extends AbstractDto {

	/**
	 *  lineNumber: 
	 */

	private Integer lineNumber;

	/**
	 *  description: 
	 */

	private String description;

	/**
	 *  lineAmount: 
	 */

	private Float lineAmount;

	/**
	 *  product: 
	 */

	private FullProductDto product = null; //pppp1

	/**
	 * Default no-argument constructor.
	 */
	public OrderlineWithRecordRefsDto() {
		super();
	}

	/**
	 * Constructor for use by the DTO Translator.
	 * 
	 * @param id
	 *            The ID of the referenced business object.
	 * @param version
	 *            The version of the referenced business object.
	 */
	public OrderlineWithRecordRefsDto(final Long id, final Integer version) {
		super(id, version);
	}

	/**
	 * @param lineNumber (Integer) 
	 */
	public void setLineNumber(final Integer lineNumber) {
		this.lineNumber = lineNumber;
	}

	/**
	 *
	 * @return lineNumber (Integer) 
	 */
	public Integer getLineNumber() {
		return this.lineNumber;
	}

	/**
	 * @param description (String) 
	 */
	public void setDescription(final String description) {
		this.description = description;
	}

	/**
	 *
	 * @return description (String) 
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * @param lineAmount (Float) 
	 */
	public void setLineAmount(final Float lineAmount) {
		this.lineAmount = lineAmount;
	}

	/**
	 *
	 * @return lineAmount (Float) 
	 */
	public Float getLineAmount() {
		return this.lineAmount;
	}

	/**
	 * @return FullProductDto (FullProductDto) 
	 */
	public FullProductDto getProduct() {
		return this.product;
	}

	/**  
	 * @param product (FullProductDto) 
	 */
	public void setProduct(final FullProductDto product) {
		this.product = product;
	}

	/**
	 * Sets all attributes that have a default value, to their default values.
	 *
	 * @author Generated by Mod4j
	 */
	public void clear() {
		lineNumber = null;
		description = null;
		lineAmount = null;

	}

	/**
	 * toString method for OrderlineWithRecordRefsDto
	 */
	@Override
	public String toString() {
		StringBuffer result = new StringBuffer();
		result
				.append("org.company.recordshop.service.dto.OrderlineWithRecordRefsDto[");
		result.append("id=");
		result.append(getId());
		result.append(",");
		result.append("version=");
		result.append(getVersion());

		result.append(",");
		result.append("lineNumber=");
		result.append(lineNumber);

		result.append(",");
		result.append("description=");
		result.append(description);

		result.append(",");
		result.append("lineAmount=");
		result.append(lineAmount);

		result.append("]");
		return result.toString();
	}

}
