
/**
 * Generated by Mod4j Service DSL: BusinessService::BusinessService at: Sun Mar 08 15:44:40 CET 2009
 * from model TestSVC
 */
package org.company.recordshop.business;
/**
 * @author Generated by Mod4j
 */
public interface TestSVCDomainService extends TestSVCDomainServiceBase {

}
