
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: OrderDto
 *     Generator        : Mod4j DatacontractDsl generator: Translators.xpt
 */

package org.company.webshop.service.dto.translators;

import java.util.HashMap;
import java.util.Map;

import org.company.webshop.domain.Order;
import org.company.webshop.domain.OrderExample;
import org.company.webshop.service.dto.OrderDto;
import org.mod4j.runtime.exception.ConcurrentUpdateException;
import org.springframework.util.Assert;

/**
 * Translator for translating Order domain objects from- and to OrderDto data transfer objects. 
 *
 * @author generated by Mod4j
 */
public class OrderDtoTranslator {

	/**
	
	 * Translates a OrderDto dto object into a Order domain object.
	 * A new domain object will be created passed to the {@link #fromDto(OrderDto, Order)}.
	.
	 *
	 * @param source The {@link OrderDto} object to translate, may not be {@code null}.
	 * @return {@link Order}, the resulting domain object.
	 */
	public Order fromDto(final OrderDto source) {
		return fromDto(source, new HashMap<Object, Object>());
	}

	Order fromDto(final OrderDto source, final Map<Object, Object> translated) {

		Assert.notNull(source, "argument [source] may not be null");
		Assert.isNull(source.getId(),
				"Can not translate a dto with existing id to a new domain object. Dto: "
						+ source);
		Order target = new Order(source.getOrderNumber()

		);
		return fromDto(source, target, translated);

	}

	/**
	 * Translates a OrderDto dto object into a Order domain object. All properties in the dto will be mapped to the 
	 * corresponding property in the <code>target</code> domain object. 
	 *
	 * @param source The {@link OrderDto} object to translate, may not be {@code null}.
	 * @param target The {@link Order} object translated from source, may not be {@code null}.
	 * @return {@link Order}, the resulting domain object.
	 */
	public Order fromDto(final OrderDto source, final Order target) {
		return fromDto(source, target, new HashMap<Object, Object>());
	}

	Order fromDto(final OrderDto source, final Order target,
			final Map<Object, Object> translated) {

		if (translated.containsKey((source))) {
			return (Order) translated.get(source);
		}

		Assert.notNull(source, "argument [source] may not be null");
		Assert.notNull(target, "argument [target] may not be null");

		final boolean equals = (source.getId() == null)
				? target.getId() == null
				: source.getId().equals(target.getId());

		if (!equals) {
			throw new IllegalArgumentException(
					"Can not translate a dto to a domain object when the id of the dto differs from the id of the domain object.");
		}

		validateVersion(source, target);

		target.activateValidation(false);

		target.setOrderNumber(source.getOrderNumber());

		target.setOrderDate(source.getOrderDate());

		target.setDeliveryDateTime(source.getDeliveryDateTime());

		target.setDiscountPercentage(source.getDiscountPercentage());

		translated.put(source, target);

		target.activateValidation(true);

		return target;
	}

	/**
	 * Translates a Order domain object into a OrderDto dto object. Properties and associations of the domain object
	 * will be mapped to the corresponding properties and associations in the dto object.
	 * To prevent looping while translating biderectional or circulair associations translated objects will be added to the 'translated' register.    
	 *
	 * @param source The {@link Order} object to translate.
	 *
	 * @return OrderDto The {@link OrderDto} object translated from source.
	 */
	public OrderDto toDto(final Order source) {
		return toDto(source, new HashMap<Object, Object>());
	}

	OrderDto toDto(final Order source, final Map<Object, Object> translated) {
		if (translated.containsKey((source))) {
			return (OrderDto) translated.get(source);
		}
		Assert.notNull(source, "argument [source] may not be null");
		OrderDto result = new OrderDto(source.getId(), source.getVersion());
		result.setOrderNumber(source.getOrderNumber());
		result.setOrderDate(source.getOrderDate());
		result.setDeliveryDateTime(source.getDeliveryDateTime());
		result.setDiscountPercentage(source.getDiscountPercentage());
		result.setTotalAmount(source.getTotalAmount());

		translated.put(source, result);

		return result;
	}

	/**
	 * Translates a OrderDto dto object into a OrderExample Example domain object. 
	 * All properties in the dto will be mapped to the corresponding property in the <code>target</code> domain object. 
	 * Association references in the dto will not be translated into the <code>target</code> domain object.
	 *
	 * @param source The {@link OrderDto} object to translate.
	 *
	 * @return {@link OrderExample}, the resulting businessclass object.
	 */
	public OrderExample exampleFromDto(final OrderDto source) {
		Assert.notNull(source, "argument [source] may not be null");
		OrderExample result = new OrderExample();

		if (source.getOrderNumber() != null) {
			result.setOrderNumber(source.getOrderNumber());
		}
		if (source.getOrderDate() != null) {
			result.setOrderDate(source.getOrderDate());
		}
		if (source.getDeliveryDateTime() != null) {
			result.setDeliveryDateTime(source.getDeliveryDateTime());
		}
		if (source.getDiscountPercentage() != null) {
			result.setDiscountPercentage(source.getDiscountPercentage());
		}

		return result;
	}

	/**
	 * Validate that the version of the DTO and the business object are valid.
	 * The DTO may only have a version if the domain object also has a version.
	 * When they both have a version and the DTO version is less, another user
	 * has updated the domain object in the meantime, if it is equal, all is
	 * well. If it is more, an unexpected situation occurs: the DTOs is more new
	 * then the domain object: this is not possible.
	 * 
	 * @param source
	 *            The DTO.
	 * @param target
	 *            The domain object target.
	 */
	private void validateVersion(final OrderDto source, final Order target) {
		final Integer sourceVersion = source.getVersion();
		final Integer targetVersion = target.getVersion();

		// FIXME the DTO translator should not know that -1 is the default unpersisted value!
		final boolean equals = (sourceVersion == null)
				? targetVersion == -1
				: sourceVersion.equals(targetVersion);

		if (!equals) {
			throw new ConcurrentUpdateException(
					"Versions of source and target do not match for dto "
							+ source + ", source is " + sourceVersion
							+ ", target is " + targetVersion + ".");
		}
	}
}
