
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: PersonDto
 *     Generator        : Mod4j DatacontractDsl generator: Translators.xpt
 */

package org.company.webshop.service.dto.translators;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.company.webshop.data.RelationDao;
import org.company.webshop.domain.Person;
import org.company.webshop.domain.PersonExample;
import org.company.webshop.domain.Relation;
import org.company.webshop.service.dto.PersonDto;
import org.company.webshop.service.dto.RelationDto;
import org.mod4j.runtime.exception.ConcurrentUpdateException;
import org.springframework.util.Assert;

/**
 * Translator for translating Person domain objects from- and to PersonDto data transfer objects. 
 *
 * @author generated by Mod4j
 */
public class PersonDtoTranslator {

	protected RelationDtoTranslator relationDtoTranslator;

	/**
	 * @param object
	 *            The relationDtoTranslator to set.
	 */
	public void setRelationDtoTranslator(RelationDtoTranslator object) {
		this.relationDtoTranslator = object;
	}

	/** 
	 * @return The relationDtoTranslator to get.
	 *
	 */
	public RelationDtoTranslator getRelationDtoTranslator() {
		return this.relationDtoTranslator;
	}

	protected RelationDao relationDao;

	/**
	 * @param object
	 *            The relationDao to set.
	 */
	public void setRelationDao(RelationDao object) {
		this.relationDao = object;
	}

	/** 
	 * @return The relationDao to get.
	 *
	 */
	public RelationDao getRelationDao() {
		return this.relationDao;
	}

	/**
	
	 * Translates a PersonDto dto object into a Person domain object.
	 * A new domain object will be created passed to the {@link #fromDto(PersonDto, Person)}.
	.
	 *
	 * @param source The {@link PersonDto} object to translate, may not be {@code null}.
	 * @return {@link Person}, the resulting domain object.
	 */
	public Person fromDto(final PersonDto source) {
		return fromDto(source, new HashMap<Object, Object>());
	}

	Person fromDto(final PersonDto source, final Map<Object, Object> translated) {

		Assert.notNull(source, "argument [source] may not be null");
		Assert.isNull(source.getId(),
				"Can not translate a dto with existing id to a new domain object. Dto: "
						+ source);
		Person target = new Person(source.getFirstName(), source.getLastName(),
				source.getBirthDate()

		);
		return fromDto(source, target, translated);

	}

	/**
	 * Translates a PersonDto dto object into a Person domain object. All properties in the dto will be mapped to the 
	 * corresponding property in the <code>target</code> domain object. 
	 *
	 * @param source The {@link PersonDto} object to translate, may not be {@code null}.
	 * @param target The {@link Person} object translated from source, may not be {@code null}.
	 * @return {@link Person}, the resulting domain object.
	 */
	public Person fromDto(final PersonDto source, final Person target) {
		return fromDto(source, target, new HashMap<Object, Object>());
	}

	Person fromDto(final PersonDto source, final Person target,
			final Map<Object, Object> translated) {

		if (translated.containsKey((source))) {
			return (Person) translated.get(source);
		}

		Assert.notNull(source, "argument [source] may not be null");
		Assert.notNull(target, "argument [target] may not be null");

		final boolean equals = (source.getId() == null)
				? target.getId() == null
				: source.getId().equals(target.getId());

		if (!equals) {
			throw new IllegalArgumentException(
					"Can not translate a dto to a domain object when the id of the dto differs from the id of the domain object.");
		}

		validateVersion(source, target);

		target.activateValidation(false);

		target.setFirstName(source.getFirstName());

		target.setLastName(source.getLastName());

		target.setBirthDate(source.getBirthDate());

		translated.put(source, target);

		/*
		 * Synchronize RelationsFrom association.
		 */
		Set<Relation> relationsFromToBeRemoved = new HashSet<Relation>();
		/* Avoid changing the collection underneath an active iterator. */
		for (Relation element : target.getRelationsFrom()) {
			if (source.getFromRelationsFrom(element.getId()) == null) {
				relationsFromToBeRemoved.add(element);
			}
		}
		/* Objects to be removed */
		for (Relation element : relationsFromToBeRemoved) {
			target.removeFromRelationsFrom(element);
		}
		for (RelationDto element : source.getRelationsFrom()) {
			if (element.getId() == null) {
				/* A new object to be added */
				target.addToRelationsFrom(relationDtoTranslator.fromDto(
						element, translated));
			} else {

				/* An existing object to be updated */
				if (target.getFromRelationsFrom(element.getId()) == null) {
					// Element is not in target yet, read it from the store and add to target
					Relation original = relationDao.retrieve(element.getId());
					Relation updated = relationDtoTranslator.fromDto(element,
							original, translated);
					target.addToRelationsFrom(updated);
				} else {
					// Element is in target already, use this object. No need to add to the collection
					relationDtoTranslator.fromDto(element, target
							.getFromRelationsFrom(element.getId()), translated);
				}
			}
		}

		/*
		 * Synchronize RelationsTo association.
		 */
		Set<Relation> relationsToToBeRemoved = new HashSet<Relation>();
		/* Avoid changing the collection underneath an active iterator. */
		for (Relation element : target.getRelationsTo()) {
			if (source.getFromRelationsTo(element.getId()) == null) {
				relationsToToBeRemoved.add(element);
			}
		}
		/* Objects to be removed */
		for (Relation element : relationsToToBeRemoved) {
			target.removeFromRelationsTo(element);
		}
		for (RelationDto element : source.getRelationsTo()) {
			if (element.getId() == null) {
				/* A new object to be added */
				target.addToRelationsTo(relationDtoTranslator.fromDto(element,
						translated));
			} else {

				/* An existing object to be updated */
				if (target.getFromRelationsTo(element.getId()) == null) {
					// Element is not in target yet, read it from the store and add to target
					Relation original = relationDao.retrieve(element.getId());
					Relation updated = relationDtoTranslator.fromDto(element,
							original, translated);
					target.addToRelationsTo(updated);
				} else {
					// Element is in target already, use this object. No need to add to the collection
					relationDtoTranslator.fromDto(element, target
							.getFromRelationsTo(element.getId()), translated);
				}
			}
		}

		target.activateValidation(true);

		return target;
	}

	/**
	 * Translates a Person domain object into a PersonDto dto object. Properties and associations of the domain object
	 * will be mapped to the corresponding properties and associations in the dto object.
	 * To prevent looping while translating biderectional or circulair associations translated objects will be added to the 'translated' register.    
	 *
	 * @param source The {@link Person} object to translate.
	 *
	 * @return PersonDto The {@link PersonDto} object translated from source.
	 */
	public PersonDto toDto(final Person source) {
		return toDto(source, new HashMap<Object, Object>());
	}

	PersonDto toDto(final Person source, final Map<Object, Object> translated) {
		if (translated.containsKey((source))) {
			return (PersonDto) translated.get(source);
		}
		Assert.notNull(source, "argument [source] may not be null");
		PersonDto result = new PersonDto(source.getId(), source.getVersion());
		result.setFirstName(source.getFirstName());
		result.setLastName(source.getLastName());
		result.setBirthDate(source.getBirthDate());

		translated.put(source, result);

		for (Relation element : source.getRelationsFrom()) {
			result.addToRelationsFrom(relationDtoTranslator.toDto(element,
					translated));
		}

		for (Relation element : source.getRelationsTo()) {
			result.addToRelationsTo(relationDtoTranslator.toDto(element,
					translated));
		}

		return result;
	}

	/**
	 * Translates a PersonDto dto object into a PersonExample Example domain object. 
	 * All properties in the dto will be mapped to the corresponding property in the <code>target</code> domain object. 
	 * Association references in the dto will not be translated into the <code>target</code> domain object.
	 *
	 * @param source The {@link PersonDto} object to translate.
	 *
	 * @return {@link PersonExample}, the resulting businessclass object.
	 */
	public PersonExample exampleFromDto(final PersonDto source) {
		Assert.notNull(source, "argument [source] may not be null");
		PersonExample result = new PersonExample();

		if (source.getFirstName() != null) {
			result.setFirstName(source.getFirstName());
		}
		if (source.getLastName() != null) {
			result.setLastName(source.getLastName());
		}
		if (source.getBirthDate() != null) {
			result.setBirthDate(source.getBirthDate());
		}

		return result;
	}

	/**
	 * Validate that the version of the DTO and the business object are valid.
	 * The DTO may only have a version if the domain object also has a version.
	 * When they both have a version and the DTO version is less, another user
	 * has updated the domain object in the meantime, if it is equal, all is
	 * well. If it is more, an unexpected situation occurs: the DTOs is more new
	 * then the domain object: this is not possible.
	 * 
	 * @param source
	 *            The DTO.
	 * @param target
	 *            The domain object target.
	 */
	private void validateVersion(final PersonDto source, final Person target) {
		final Integer sourceVersion = source.getVersion();
		final Integer targetVersion = target.getVersion();

		// FIXME the DTO translator should not know that -1 is the default unpersisted value!
		final boolean equals = (sourceVersion == null)
				? targetVersion == -1
				: sourceVersion.equals(targetVersion);

		if (!equals) {
			throw new ConcurrentUpdateException(
					"Versions of source and target do not match for dto "
							+ source + ", source is " + sourceVersion
							+ ", target is " + targetVersion + ".");
		}
	}
}
