
/**
 * Initially generated by Mod4j at Sat Mar 07 22:20:49 CET 2009
 */
package org.company.recordshop.data.hibernate.spring;

import org.company.recordshop.data.DerivedNotYetImplementedDao;

/**
 * DerivedNotYetImplemented Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting DerivedNotYetImplemented objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class DerivedNotYetImplementedDaoImpl
		extends
			DerivedNotYetImplementedDaoImplBase
		implements
			DerivedNotYetImplementedDao {

}
