
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:15 CEST 2011
 *     Application model: TestSVC
 *     Generator        : Mod4j ServiceDsl generator: BusinessServiceImplBase.xpt
 */

package org.company.recordshop.business;

import java.util.List;

import org.company.recordshop.data.DerivedDao;
import org.company.recordshop.domain.Derived;
import org.springframework.util.Assert;

/**
 * @author Generated by Mod4j
 */
abstract public class TestSVCDomainServiceImplBase
		implements
			TestSVCDomainServiceBase {

	protected DerivedDao derivedDao;

	/**
	 * @param object
	 *            The derivedDao to set.
	 */
	public void setDerivedDao(DerivedDao object) {
		this.derivedDao = object;
	}

	/** 
	 * @return The derivedDao to get.
	 *
	 */
	public DerivedDao getDerivedDao() {
		return this.derivedDao;
	}

	/**
	 * {@inheritDoc} 
	 */
	public Long createDerived(Derived object) {
		Assert.notNull(object, "argument [object] may not be null");
		return derivedDao.add(object);
	}

	/**
	 * {@inheritDoc} 
	 */
	public Derived readDerived(Long id) {
		Assert.notNull(id, "argument [id] may not be null");
		return derivedDao.retrieve(id);
	}

	/**
	 * {@inheritDoc} 
	 */
	public void updateDerived(Derived object) {
		Assert.notNull(object, "argument [object] may not be null");
	}

	/**
	 * {@inheritDoc} 
	 */
	public void deleteDerived(Derived object) {
		Assert.notNull(object, "argument [object] may not be null");
		derivedDao.delete(object);
	}

	/**
	 * {@inheritDoc} 
	 */
	public List<Derived> listAllDeriveds() {
		return derivedDao.listAll();
	}

	/**
	 * {@inheritDoc} 
	 */
	public List<Derived> listDeriveds(final int firstResult,
			final int maxResults) {
		return derivedDao.listPage(firstResult, maxResults);
	}

	/**
	 * {@inheritDoc} 
	 */
	public List<Derived> listDeriveds(final int firstResult,
			final int maxResults, final String sortProperty,
			final boolean isAscending) {
		return derivedDao.listPage(firstResult, maxResults, sortProperty,
				isAscending);
	}

	/**
	 * {@inheritDoc} 
	 */
	public long countDeriveds() {
		return derivedDao.count();
	}

}
