
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:42 CEST 2010
 *     Application model: AnotherRule
 *     Generator        :  Mod4j BusinessDomainDsl genrator: NewBusinessRules.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain.businessrules;

import org.springframework.validation.Errors;

/**
 * Just another rule
 * 
 */
public class AnotherRule extends AnotherRuleImplBase {

	/**
	 *  {@inheritDoc} 
	 */
	public void validate(Object target, Errors errors) {
		// TODO Implement validation code for business rule AnotherRule.
	}

}
