/** 
 * Initially generated by Mod4j at Thu Feb 26 16:47:48 CET 2009
 */
package org.company.recordshop.data;

/**
 * Many2ManyFromDao Data Access Object (DAO). Responsible for accessing the database.
 *
 * This interface is intended to be manually changed by developers. 
 * 
 * @author Initially generated by Mod4j
 * 
 */
public interface Many2ManyFromDao extends Many2ManyFromDaoBase {

}
