/**
 * Generated by Mod4j Service DSL: BusinessService::BusinessService at: Tue Feb 10 13:56:29 CET 2009
 * from model OrderServiceModel
 */
package org.company.webshop.business;

import org.company.webshop.business.OrderServiceModelDomainServiceBase;

/**
 * @author Generated by Mod4j
 */
public interface OrderServiceModelDomainService
		extends
			OrderServiceModelDomainServiceBase {

}
