
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:35 CEST 2010
 *     Application model: StateChangeBusinessRule
 *     Generator        :  Mod4j ServiceDsl generator: BusinessServiceImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.webshop.business;

import org.company.webshop.business.StateChangeBusinessRuleDomainServiceImplBase;


/**
 * @author Generated by Mod4j, use as extension point to implement custom business services
 */
public class StateChangeBusinessRuleDomainServiceImpl
		extends
			StateChangeBusinessRuleDomainServiceImplBase
		implements
			StateChangeBusinessRuleDomainService {

}
