
/**
 * Generated by Mod4j Service DSL: BusinessServiceImpl::BusinessServiceImpl at: Sun Mar 08 15:44:41 CET 2009
 * from model TestSVC
 */
package org.company.webshop.business;

import org.company.webshop.business.TestSVCDomainServiceImplBase;


/**
 * @author Generated by Mod4j, use as extension point to implement custom business services
 */
public class TestSVCDomainServiceImpl extends TestSVCDomainServiceImplBase
		implements
			TestSVCDomainService {

}
