
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Wed Oct 21 19:35:57 CEST 2009
 *     Application model: MyDerived
 *     Generator        :  Mod4j BusinessDomainDsl generator: DaoImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j.
 */

package org.company.recordshop.data;

/**
 * MyDerivedDao Data Access Object (DAO). Responsible for accessing the database.
 *
 * This interface is intended to be manually changed by developers. 
 * 
 * @author Initially generated by Mod4j
 * 
 */
public interface MyDerivedDao extends MyDerivedDaoBase {
}
