
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: CasusOverleg
 *     Generator        : Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 */

package org.company.recordshop.domain;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import org.joda.time.DateTime;
import org.mod4j.runtime.validation.BusinessRuleValidationSupport;
import org.mod4j.runtime.validation.NotNullValidator;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
@SuppressWarnings("serial")
public abstract class CasusOverlegImplBase implements java.io.Serializable {

	/**
	 * validation : Responsible for validating attribute constraints and businessrules for this business class.
	 * 
	 */
	protected BusinessRuleValidationSupport validation = new BusinessRuleValidationSupport(
			this);

	/**
	 *  id: The identifier of this object.
	 */
	private Long id;

	/**
	 *
	 * @return id (Long) The identifier of this object.
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * version: The version of this object 
	 */
	private int version = -1;

	/**
	 * @return version (Integer) The version of this object.
	 */
	public Integer getVersion() {
		return this.version;
	}

	/**
	 * toString method for CasusOverlegImplBase
	 */
	@Override
	public String toString() {
		StringBuffer result = new StringBuffer();
		result.append("org.company.recordshop.domain.CasusOverleg[");
		result.append("id=");
		result.append(getId());
		result.append(",");
		result.append("version=");
		result.append(getVersion());

		result.append(",");
		result.append("naam=");
		result.append(naam);

		result.append(",");
		result.append("datum=");
		result.append(datum);

		result.append("]");
		return result.toString();
	}

	/**
	 *  naam: 
	 */
	protected String naam;

	/**
	 *  datum: 
	 */
	protected DateTime datum;

	/**
	 *  organisaties: 
	 */
	private Set<Organisatie> organisaties = new HashSet<Organisatie>();

	/**
	 * @return organisaties (Set<Organisatie>).
	 */
	public Set<Organisatie> getOrganisaties() {
		return Collections.unmodifiableSet(this.organisaties);
	}

	/**
	 * @param id
	 *        id of the collection element to return
	 *
	 * @return organisaties (Set<Organisatie>)
	 * @return organisaties (Set<Organisatie>)
	 *         with the given id.
	 */
	public Organisatie getFromOrganisaties(Long id) {
		if (id == null) {
			return null;
		}
		for (Organisatie organisatie : this.organisaties) {
			if (id.equals(organisatie.getId())) {
				return organisatie;
			}
		}
		return null;
	}

	/**
	 * Implements adding single element to a collection.
	 */
	public boolean addToOrganisaties(Organisatie element) {
		if (element == null) {
			return false;
		}
		if (!organisaties.contains(element)) {
			organisaties.add(element);
			element.addToOverleggen((CasusOverleg) this);
			validation.validate();
			return true;
		}
		return false;
	}

	/**
	 * Implements removing a single element from a collection.
	 */
	public boolean removeFromOrganisaties(Organisatie element) {
		if (element == null) {
			return false;
		}
		if (organisaties.contains(element)) {
			this.organisaties.remove(element);
			element.removeFromOverleggen((CasusOverleg) this);
			validation.validate();
			return true;
		}
		return false;
	}

	private void addValidators() {

		validation
				.addValidator(new NotNullValidator(CasusOverleg.class, "naam"));

		validation.addValidator(new NotNullValidator(CasusOverleg.class,
				"datum"));

	}

	/**
	 * Default no-argument constructor for CasusOverlegImplBase 
	 */
	protected CasusOverlegImplBase() {

		addValidators();
	}

	/**
	 * Minimal constructor for CasusOverlegImplBase
	 *
	 * @param naam (String) 
	 * @param datum (DateTime) 
	 */
	public CasusOverlegImplBase(String naam, DateTime datum) {

		this.naam = naam;
		this.datum = datum;
		addValidators();
		validation.validate();
	}

	/**
	 * @return naam (String) 
	 */
	public String getNaam() {
		return this.naam;
	}

	/**
	 * @return datum (DateTime) 
	 */
	public DateTime getDatum() {
		return this.datum;
	}

	/**
	 * @param naam (String) 
	 */
	public void setNaam(final String naam) {
		this.naam = naam;
		validation.validate();
	}

	/**
	 * @param datum (DateTime) 
	 */
	public void setDatum(final DateTime datum) {
		this.datum = datum;
		validation.validate();
	}

	/**
	 * Activate/deactivate validation for this business class.
	 * When set to active the validation will immediately be executed.
	 * 
	 * @param value (boolean) 
	 */
	public void activateValidation(boolean value) {

		this.validation.setActive(value);
		if (value) {
			validation.validate();
		}
	}

}
