
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:09 CEST 2011
 *     Application model: RecordTypeEnum
 *     Generator        : Mod4j BusinessDomainDsl generator: Enumeration.xpt
 */

package org.company.recordshop.domain;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

/**
 * 
 *
 */
public enum RecordTypeEnum {

	LP(2), CD(3), DVD(4), BLUERAY(5);

	private static final Map<Integer, RecordTypeEnum> lookup = new HashMap<Integer, RecordTypeEnum>();
	static {
		for (RecordTypeEnum s : EnumSet.allOf(RecordTypeEnum.class))
			lookup.put(s.id(), s);
	}

	private Integer id;

	private RecordTypeEnum(Integer id) {
		this.id = id;
	}

	public Integer id() {
		return id;
	}

	public static RecordTypeEnum value(Integer id) {
		return lookup.get(id);
	}
}
