
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: Subclass2
 *     Generator        : Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 */

package org.company.recordshop.domain;


/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
@SuppressWarnings("serial")
public abstract class Subclass2ImplBase extends Subclass
		implements
			java.io.Serializable {

	/**
	 * toString method for Subclass2ImplBase
	 */
	@Override
	public String toString() {
		StringBuffer result = new StringBuffer();
		result.append("org.company.recordshop.domain.Subclass2[");
		result.append("id=");
		result.append(getId());
		result.append(",");
		result.append("version=");
		result.append(getVersion());

		result.append(",");
		result.append("name=");
		result.append(name);

		result.append(",");
		result.append("active=");
		result.append(active);

		result.append("]");
		return result.toString();
	}

	private void addValidators() {

	}

	/**
	 * Default no-argument constructor for Subclass2ImplBase 
	 */
	protected Subclass2ImplBase() {
		super();
		addValidators();
	}

	/**
	 * Minimal constructor for Subclass2ImplBase
	 *
	 * @param name (String) 
	 */
	public Subclass2ImplBase(String name) {
		super(name);

		addValidators();
		validation.validate();
	}

	/**
	 * Activate/deactivate validation for this business class.
	 * When set to active the validation will immediately be executed.
	 * 
	 * @param value (boolean) 
	 */
	public void activateValidation(boolean value) {

		this.validation.setActive(value);
		if (value) {
			validation.validate();
		}
	}

}
