
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:12 CEST 2011
 *     Application model: FullCustomerDto
 *     Generator        : Mod4j DatacontractDsl generator: Translators.xpt
 */

package org.company.recordshop.service.dto.translators;

import java.util.HashMap;
import java.util.Map;

import org.company.recordshop.domain.Customer;
import org.company.recordshop.domain.CustomerExample;
import org.company.recordshop.service.dto.FullCustomerDto;
import org.mod4j.runtime.exception.ConcurrentUpdateException;
import org.springframework.util.Assert;

/**
 * Translator for translating Customer domain objects from- and to FullCustomerDto data transfer objects. 
 *
 * @author generated by Mod4j
 */
public class FullCustomerDtoTranslator {

	private SexeEnumDtoTranslator sexeTranslator = new SexeEnumDtoTranslator();

	/**
	
	 * Translates a FullCustomerDto dto object into a Customer domain object.
	 * A new domain object will be created passed to the {@link #fromDto(FullCustomerDto, Customer)}.
	.
	 *
	 * @param source The {@link FullCustomerDto} object to translate, may not be {@code null}.
	 * @return {@link Customer}, the resulting domain object.
	 */
	public Customer fromDto(final FullCustomerDto source) {
		return fromDto(source, new HashMap<Object, Object>());
	}

	Customer fromDto(final FullCustomerDto source,
			final Map<Object, Object> translated) {

		Assert.notNull(source, "argument [source] may not be null");
		Assert.isNull(source.getId(),
				"Can not translate a dto with existing id to a new domain object. Dto: "
						+ source);
		Customer target = new Customer(source.getFirstName(), source
				.getLastName(), source.getBirthDate(), source.getCustomerNr()

		);
		return fromDto(source, target, translated);

	}

	/**
	 * Translates a FullCustomerDto dto object into a Customer domain object. All properties in the dto will be mapped to the 
	 * corresponding property in the <code>target</code> domain object. 
	 *
	 * @param source The {@link FullCustomerDto} object to translate, may not be {@code null}.
	 * @param target The {@link Customer} object translated from source, may not be {@code null}.
	 * @return {@link Customer}, the resulting domain object.
	 */
	public Customer fromDto(final FullCustomerDto source, final Customer target) {
		return fromDto(source, target, new HashMap<Object, Object>());
	}

	Customer fromDto(final FullCustomerDto source, final Customer target,
			final Map<Object, Object> translated) {

		if (translated.containsKey((source))) {
			return (Customer) translated.get(source);
		}

		Assert.notNull(source, "argument [source] may not be null");
		Assert.notNull(target, "argument [target] may not be null");

		final boolean equals = (source.getId() == null)
				? target.getId() == null
				: source.getId().equals(target.getId());

		if (!equals) {
			throw new IllegalArgumentException(
					"Can not translate a dto to a domain object when the id of the dto differs from the id of the domain object.");
		}

		validateVersion(source, target);

		target.activateValidation(false);

		target.setCustomerNr(source.getCustomerNr());

		target.setUsername(source.getUsername());

		target.setEmailAddress(source.getEmailAddress());

		target.setBlackListed(source.isBlackListed());

		if (source.getDiscountPercentage() != null) {
			target.setDiscountPercentage(source.getDiscountPercentage());
		}
		target.setFirstName(source.getFirstName());

		target.setLastName(source.getLastName());

		target.setBirthDate(source.getBirthDate());

		if (source.getNumberOfEars() != null) {
			target.setNumberOfEars(source.getNumberOfEars());
		}
		target.setSexe(sexeTranslator.fromDto(source.getSexe()));

		translated.put(source, target);

		target.activateValidation(true);

		return target;
	}

	/**
	 * Translates a Customer domain object into a FullCustomerDto dto object. Properties and associations of the domain object
	 * will be mapped to the corresponding properties and associations in the dto object.
	 * To prevent looping while translating biderectional or circulair associations translated objects will be added to the 'translated' register.    
	 *
	 * @param source The {@link Customer} object to translate.
	 *
	 * @return FullCustomerDto The {@link FullCustomerDto} object translated from source.
	 */
	public FullCustomerDto toDto(final Customer source) {
		return toDto(source, new HashMap<Object, Object>());
	}

	FullCustomerDto toDto(final Customer source,
			final Map<Object, Object> translated) {
		if (translated.containsKey((source))) {
			return (FullCustomerDto) translated.get(source);
		}
		Assert.notNull(source, "argument [source] may not be null");
		FullCustomerDto result = new FullCustomerDto(source.getId(), source
				.getVersion());
		result.setCustomerNr(source.getCustomerNr());
		result.setUsername(source.getUsername());
		result.setEmailAddress(source.getEmailAddress());
		result.setBlackListed(source.isBlackListed());
		result.setDiscountPercentage(source.getDiscountPercentage());
		result.setFirstName(source.getFirstName());
		result.setLastName(source.getLastName());
		result.setBirthDate(source.getBirthDate());
		result.setAge(source.getAge());
		result.setNumberOfEars(source.getNumberOfEars());
		result.setSexe(sexeTranslator.toDto(source.getSexe()));

		translated.put(source, result);

		return result;
	}

	/**
	 * Translates a FullCustomerDto dto object into a CustomerExample Example domain object. 
	 * All properties in the dto will be mapped to the corresponding property in the <code>target</code> domain object. 
	 * Association references in the dto will not be translated into the <code>target</code> domain object.
	 *
	 * @param source The {@link FullCustomerDto} object to translate.
	 *
	 * @return {@link CustomerExample}, the resulting businessclass object.
	 */
	public CustomerExample exampleFromDto(final FullCustomerDto source) {
		Assert.notNull(source, "argument [source] may not be null");
		CustomerExample result = new CustomerExample();

		if (source.getCustomerNr() != null) {
			result.setCustomerNr(source.getCustomerNr());
		}
		if (source.getUsername() != null) {
			result.setUsername(source.getUsername());
		}
		if (source.getEmailAddress() != null) {
			result.setEmailAddress(source.getEmailAddress());
		}
		if (source.isBlackListed() != null) {
			result.setBlackListed(source.isBlackListed());
		}
		if (source.getDiscountPercentage() != null) {
			result.setDiscountPercentage(source.getDiscountPercentage());
		}
		if (source.getFirstName() != null) {
			result.setFirstName(source.getFirstName());
		}
		if (source.getLastName() != null) {
			result.setLastName(source.getLastName());
		}
		if (source.getBirthDate() != null) {
			result.setBirthDate(source.getBirthDate());
		}
		if (source.getNumberOfEars() != null) {
			result.setNumberOfEars(source.getNumberOfEars());
		}
		if (source.getSexe() != null) {
			result.setSexe(sexeTranslator.fromDto(source.getSexe()));
		}

		return result;
	}

	/**
	 * Validate that the version of the DTO and the business object are valid.
	 * The DTO may only have a version if the domain object also has a version.
	 * When they both have a version and the DTO version is less, another user
	 * has updated the domain object in the meantime, if it is equal, all is
	 * well. If it is more, an unexpected situation occurs: the DTOs is more new
	 * then the domain object: this is not possible.
	 * 
	 * @param source
	 *            The DTO.
	 * @param target
	 *            The domain object target.
	 */
	private void validateVersion(final FullCustomerDto source,
			final Customer target) {
		final Integer sourceVersion = source.getVersion();
		final Integer targetVersion = target.getVersion();

		// FIXME the DTO translator should not know that -1 is the default unpersisted value!
		final boolean equals = (sourceVersion == null)
				? targetVersion == -1
				: sourceVersion.equals(targetVersion);

		if (!equals) {
			throw new ConcurrentUpdateException(
					"Versions of source and target do not match for dto "
							+ source + ", source is " + sourceVersion
							+ ", target is " + targetVersion + ".");
		}
	}
}
