
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:13 CEST 2011
 *     Application model: KaderDto
 *     Generator        : Mod4j DatacontractDsl generator: Translators.xpt
 */

package org.company.recordshop.service.dto.translators;

import java.util.HashMap;
import java.util.Map;
import java.util.HashSet;
import java.util.Set;
import org.springframework.util.Assert;
import org.mod4j.runtime.exception.ConcurrentUpdateException;
import org.company.recordshop.domain.Kader;
import org.company.recordshop.domain.KaderExample;
import org.company.recordshop.service.dto.KaderDto;
import org.company.recordshop.domain.Organisatie;
import org.company.recordshop.service.dto.OrganisatieDto;

import org.company.recordshop.data.OrganisatieDao;

/**
 * Translator for translating Kader domain objects from- and to KaderDto data transfer objects. 
 *
 * @author generated by Mod4j
 */
public class KaderDtoTranslator {

	protected OrganisatieDtoTranslator organisatieDtoTranslator;

	/**
	 * @param object
	 *            The organisatieDtoTranslator to set.
	 */
	public void setOrganisatieDtoTranslator(OrganisatieDtoTranslator object) {
		this.organisatieDtoTranslator = object;
	}

	/** 
	 * @return The organisatieDtoTranslator to get.
	 *
	 */
	public OrganisatieDtoTranslator getOrganisatieDtoTranslator() {
		return this.organisatieDtoTranslator;
	}

	protected OrganisatieDao organisatieDao;

	/**
	 * @param object
	 *            The organisatieDao to set.
	 */
	public void setOrganisatieDao(OrganisatieDao object) {
		this.organisatieDao = object;
	}

	/** 
	 * @return The organisatieDao to get.
	 *
	 */
	public OrganisatieDao getOrganisatieDao() {
		return this.organisatieDao;
	}

	/**
	
	 * Translates a KaderDto dto object into a Kader domain object.
	 * A new domain object will be created passed to the {@link #fromDto(KaderDto, Kader)}.
	.
	 *
	 * @param source The {@link KaderDto} object to translate, may not be {@code null}.
	 * @return {@link Kader}, the resulting domain object.
	 */
	public Kader fromDto(final KaderDto source) {
		return fromDto(source, new HashMap<Object, Object>());
	}

	Kader fromDto(final KaderDto source, final Map<Object, Object> translated) {

		Assert.notNull(source, "argument [source] may not be null");
		Assert.isNull(source.getId(),
				"Can not translate a dto with existing id to a new domain object. Dto: "
						+ source);
		Kader target = new Kader(source.getNaam()

		);
		return fromDto(source, target, translated);

	}

	/**
	 * Translates a KaderDto dto object into a Kader domain object. All properties in the dto will be mapped to the 
	 * corresponding property in the <code>target</code> domain object. 
	 *
	 * @param source The {@link KaderDto} object to translate, may not be {@code null}.
	 * @param target The {@link Kader} object translated from source, may not be {@code null}.
	 * @return {@link Kader}, the resulting domain object.
	 */
	public Kader fromDto(final KaderDto source, final Kader target) {
		return fromDto(source, target, new HashMap<Object, Object>());
	}

	Kader fromDto(final KaderDto source, final Kader target,
			final Map<Object, Object> translated) {

		if (translated.containsKey((source))) {
			return (Kader) translated.get(source);
		}

		Assert.notNull(source, "argument [source] may not be null");
		Assert.notNull(target, "argument [target] may not be null");

		final boolean equals = (source.getId() == null)
				? target.getId() == null
				: source.getId().equals(target.getId());

		if (!equals) {
			throw new IllegalArgumentException(
					"Can not translate a dto to a domain object when the id of the dto differs from the id of the domain object.");
		}

		validateVersion(source, target);

		target.activateValidation(false);

		target.setNaam(source.getNaam());

		translated.put(source, target);

		/*
		 * Synchronize Organisaties association.
		 */
		Set<Organisatie> organisatiesToBeRemoved = new HashSet<Organisatie>();
		/* Avoid changing the collection underneath an active iterator. */
		for (Organisatie element : target.getOrganisaties()) {
			if (source.getFromOrganisaties(element.getId()) == null) {
				organisatiesToBeRemoved.add(element);
			}
		}
		/* Objects to be removed */
		for (Organisatie element : organisatiesToBeRemoved) {
			target.removeFromOrganisaties(element);
		}
		for (OrganisatieDto element : source.getOrganisaties()) {
			if (element.getId() == null) {
				/* A new object to be added */
				target.addToOrganisaties(organisatieDtoTranslator.fromDto(
						element, translated));
			} else {

				/* An existing object to be updated */
				if (target.getFromOrganisaties(element.getId()) == null) {
					// Element is not in target yet, read it from the store and add to target
					Organisatie original = organisatieDao.retrieve(element
							.getId());
					Organisatie updated = organisatieDtoTranslator.fromDto(
							element, original, translated);
					target.addToOrganisaties(updated);
				} else {
					// Element is in target already, use this object. No need to add to the collection
					organisatieDtoTranslator.fromDto(element, target
							.getFromOrganisaties(element.getId()), translated);
				}
			}
		}

		target.activateValidation(true);

		return target;
	}

	/**
	 * Translates a Kader domain object into a KaderDto dto object. Properties and associations of the domain object
	 * will be mapped to the corresponding properties and associations in the dto object.
	 * To prevent looping while translating biderectional or circulair associations translated objects will be added to the 'translated' register.    
	 *
	 * @param source The {@link Kader} object to translate.
	 *
	 * @return KaderDto The {@link KaderDto} object translated from source.
	 */
	public KaderDto toDto(final Kader source) {
		return toDto(source, new HashMap<Object, Object>());
	}

	KaderDto toDto(final Kader source, final Map<Object, Object> translated) {
		if (translated.containsKey((source))) {
			return (KaderDto) translated.get(source);
		}
		Assert.notNull(source, "argument [source] may not be null");
		KaderDto result = new KaderDto(source.getId(), source.getVersion());
		result.setNaam(source.getNaam());

		translated.put(source, result);

		for (Organisatie element : source.getOrganisaties()) {
			result.addToOrganisaties(organisatieDtoTranslator.toDto(element,
					translated));
		}

		return result;
	}

	/**
	 * Translates a KaderDto dto object into a KaderExample Example domain object. 
	 * All properties in the dto will be mapped to the corresponding property in the <code>target</code> domain object. 
	 * Association references in the dto will not be translated into the <code>target</code> domain object.
	 *
	 * @param source The {@link KaderDto} object to translate.
	 *
	 * @return {@link KaderExample}, the resulting businessclass object.
	 */
	public KaderExample exampleFromDto(final KaderDto source) {
		Assert.notNull(source, "argument [source] may not be null");
		KaderExample result = new KaderExample();

		if (source.getNaam() != null) {
			result.setNaam(source.getNaam());
		}

		return result;
	}

	/**
	 * Validate that the version of the DTO and the business object are valid.
	 * The DTO may only have a version if the domain object also has a version.
	 * When they both have a version and the DTO version is less, another user
	 * has updated the domain object in the meantime, if it is equal, all is
	 * well. If it is more, an unexpected situation occurs: the DTOs is more new
	 * then the domain object: this is not possible.
	 * 
	 * @param source
	 *            The DTO.
	 * @param target
	 *            The domain object target.
	 */
	private void validateVersion(final KaderDto source, final Kader target) {
		final Integer sourceVersion = source.getVersion();
		final Integer targetVersion = target.getVersion();

		// FIXME the DTO translator should not know that -1 is the default unpersisted value!
		final boolean equals = (sourceVersion == null)
				? targetVersion == -1
				: sourceVersion.equals(targetVersion);

		if (!equals) {
			throw new ConcurrentUpdateException(
					"Versions of source and target do not match for dto "
							+ source + ", source is " + sourceVersion
							+ ", target is " + targetVersion + ".");
		}
	}
}
