/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:11 CEST 2011
 *     Application model: DerivedNotYetImplemented
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.recordshop.data;

import java.util.List;

import org.company.recordshop.domain.DerivedNotYetImplemented;
import org.company.recordshop.domain.DerivedNotYetImplementedExample;

/**
 * DerivedNotYetImplementedDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface DerivedNotYetImplementedDaoBase {

	/**
	 * Retrieves a DerivedNotYetImplemented by its ID from the database.
	 * 
	 * @param id id of the DerivedNotYetImplemented to retrieve.
	 * @return DerivedNotYetImplemented retrieved or null when no DerivedNotYetImplemented was found.
	 */
	DerivedNotYetImplemented retrieve(Long id);

	/**
	 * Adds a new DerivedNotYetImplemented to the database
	 * 
	 * @param object
	 *                the DerivedNotYetImplemented to add to the database.
	 * @return the stored DerivedNotYetImplemented.
	 */
	Long add(DerivedNotYetImplemented object);

	/**
	 * Deletes a DerivedNotYetImplemented from the database.
	 * 
	 * @param object
	 *                the DerivedNotYetImplemented to delete
	 */
	void delete(DerivedNotYetImplemented object);

	/**
	 * Selects all DerivedNotYetImplementeds from the database.
	 * 
	 * @return a List of all DerivedNotYetImplemented objects.
	 */
	List<DerivedNotYetImplemented> listAll();

	/**
	 * Selects a range (page) of DerivedNotYetImplementeds from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more DerivedNotYetImplemented objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<DerivedNotYetImplemented> listPage(final int firstResult,
			final int maxResults);

	/**
	 * Selects a sorted range (page) of DerivedNotYetImplementeds from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more DerivedNotYetImplemented objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<DerivedNotYetImplemented> listPage(final int firstResult,
			final int maxResults, final String sortProperty,
			final boolean isAscending);

	/**
	 * Selects a sorted range (page) of DerivedNotYetImplementeds from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more DerivedNotYetImplemented objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<DerivedNotYetImplemented> listPageByExample(
			final DerivedNotYetImplementedExample example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted DerivedNotYetImplemented objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted DerivedNotYetImplemented objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final DerivedNotYetImplementedExample example);

	/**
	 * Selects DerivedNotYetImplementeds from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of DerivedNotYetImplemented objects.
	 */
	List<DerivedNotYetImplemented> findByExample(
			DerivedNotYetImplementedExample example);
}
