/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: Empty
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.recordshop.data;

import java.util.List;

import org.company.recordshop.domain.Empty;
import org.company.recordshop.domain.EmptyExample;

/**
 * EmptyDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface EmptyDaoBase {

	/**
	 * Retrieves a Empty by its ID from the database.
	 * 
	 * @param id id of the Empty to retrieve.
	 * @return Empty retrieved or null when no Empty was found.
	 */
	Empty retrieve(Long id);

	/**
	 * Adds a new Empty to the database
	 * 
	 * @param object
	 *                the Empty to add to the database.
	 * @return the stored Empty.
	 */
	Long add(Empty object);

	/**
	 * Deletes a Empty from the database.
	 * 
	 * @param object
	 *                the Empty to delete
	 */
	void delete(Empty object);

	/**
	 * Selects all Emptys from the database.
	 * 
	 * @return a List of all Empty objects.
	 */
	List<Empty> listAll();

	/**
	 * Selects a range (page) of Emptys from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more Empty objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<Empty> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of Emptys from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Empty objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Empty> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of Emptys from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Empty objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Empty> listPageByExample(final EmptyExample example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted Empty objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted Empty objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final EmptyExample example);

	/**
	 * Selects Emptys from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of Empty objects.
	 */
	List<Empty> findByExample(EmptyExample example);
}
