/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:11 CEST 2011
 *     Application model: One2ManyFrom
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.recordshop.data;

import java.util.List;

import org.company.recordshop.domain.One2ManyFrom;
import org.company.recordshop.domain.One2ManyFromExample;

/**
 * One2ManyFromDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface One2ManyFromDaoBase {

	/**
	 * Retrieves a One2ManyFrom by its ID from the database.
	 * 
	 * @param id id of the One2ManyFrom to retrieve.
	 * @return One2ManyFrom retrieved or null when no One2ManyFrom was found.
	 */
	One2ManyFrom retrieve(Long id);

	/**
	 * Adds a new One2ManyFrom to the database
	 * 
	 * @param object
	 *                the One2ManyFrom to add to the database.
	 * @return the stored One2ManyFrom.
	 */
	Long add(One2ManyFrom object);

	/**
	 * Deletes a One2ManyFrom from the database.
	 * 
	 * @param object
	 *                the One2ManyFrom to delete
	 */
	void delete(One2ManyFrom object);

	/**
	 * Selects all One2ManyFroms from the database.
	 * 
	 * @return a List of all One2ManyFrom objects.
	 */
	List<One2ManyFrom> listAll();

	/**
	 * Selects a range (page) of One2ManyFroms from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more One2ManyFrom objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<One2ManyFrom> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of One2ManyFroms from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more One2ManyFrom objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<One2ManyFrom> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of One2ManyFroms from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more One2ManyFrom objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<One2ManyFrom> listPageByExample(final One2ManyFromExample example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted One2ManyFrom objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted One2ManyFrom objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final One2ManyFromExample example);

	/**
	 * Selects One2ManyFroms from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of One2ManyFrom objects.
	 */
	List<One2ManyFrom> findByExample(One2ManyFromExample example);
}
