/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: Product
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.recordshop.data;

import java.util.List;

import org.company.recordshop.domain.Product;
import org.company.recordshop.domain.ProductExample;

/**
 * ProductDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface ProductDaoBase {

	/**
	 * Retrieves a Product by its ID from the database.
	 * 
	 * @param id id of the Product to retrieve.
	 * @return Product retrieved or null when no Product was found.
	 */
	Product retrieve(Long id);

	/**
	 * Adds a new Product to the database
	 * 
	 * @param object
	 *                the Product to add to the database.
	 * @return the stored Product.
	 */
	Long add(Product object);

	/**
	 * Deletes a Product from the database.
	 * 
	 * @param object
	 *                the Product to delete
	 */
	void delete(Product object);

	/**
	 * Selects all Products from the database.
	 * 
	 * @return a List of all Product objects.
	 */
	List<Product> listAll();

	/**
	 * Selects a range (page) of Products from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more Product objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<Product> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of Products from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Product objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Product> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of Products from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Product objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Product> listPageByExample(final ProductExample example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted Product objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted Product objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final ProductExample example);

	/**
	 * Selects Products from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of Product objects.
	 */
	List<Product> findByExample(ProductExample example);
}
