/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:09 CEST 2011
 *     Application model: Record
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.recordshop.data;

import java.util.List;

import org.company.recordshop.domain.Record;
import org.company.recordshop.domain.RecordExample;

/**
 * RecordDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface RecordDaoBase {

	/**
	 * Retrieves a Record by its ID from the database.
	 * 
	 * @param id id of the Record to retrieve.
	 * @return Record retrieved or null when no Record was found.
	 */
	Record retrieve(Long id);

	/**
	 * Adds a new Record to the database
	 * 
	 * @param object
	 *                the Record to add to the database.
	 * @return the stored Record.
	 */
	Long add(Record object);

	/**
	 * Deletes a Record from the database.
	 * 
	 * @param object
	 *                the Record to delete
	 */
	void delete(Record object);

	/**
	 * Selects all Records from the database.
	 * 
	 * @return a List of all Record objects.
	 */
	List<Record> listAll();

	/**
	 * Selects a range (page) of Records from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more Record objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<Record> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of Records from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Record objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Record> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of Records from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Record objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Record> listPageByExample(final RecordExample example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted Record objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted Record objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final RecordExample example);

	/**
	 * Selects Records from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of Record objects.
	 */
	List<Record> findByExample(RecordExample example);
}
