/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:10 CEST 2011
 *     Application model: Subclass
 *     Generator        : Mod4j BusinessDomainDsl generator: DaoInterfaceBase.xpt
 */

package org.company.recordshop.data;

import java.util.List;

import org.company.recordshop.domain.Subclass;
import org.company.recordshop.domain.SubclassExample;

/**
 * SubclassDaoBaseData Access Object (DAO). Responsible for accessing database.
 * 
 * @author Mod4j generated
 * 
 */
public interface SubclassDaoBase {

	/**
	 * Retrieves a Subclass by its ID from the database.
	 * 
	 * @param id id of the Subclass to retrieve.
	 * @return Subclass retrieved or null when no Subclass was found.
	 */
	Subclass retrieve(Long id);

	/**
	 * Adds a new Subclass to the database
	 * 
	 * @param object
	 *                the Subclass to add to the database.
	 * @return the stored Subclass.
	 */
	Long add(Subclass object);

	/**
	 * Deletes a Subclass from the database.
	 * 
	 * @param object
	 *                the Subclass to delete
	 */
	void delete(Subclass object);

	/**
	 * Selects all Subclasss from the database.
	 * 
	 * @return a List of all Subclass objects.
	 */
	List<Subclass> listAll();

	/**
	 * Selects a range (page) of Subclasss from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults  the maximum number of result objects to retrieve (or <=0 for no limit) 
	 * 
	 * @return a List containing 0 or more Subclass objects.
	 *
	 * @see #listPage(int, int)
	 */
	List<Subclass> listPage(final int firstResult, final int maxResults);

	/**
	 * Selects a sorted range (page) of Subclasss from the database.
	 * 
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Subclass objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Subclass> listPage(final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Selects a sorted range (page) of Subclasss from the database.
	 * 
	 * @param example the example object to which the result objects need to conform
	 * @param firstResult the index of the first result object to be retrieved (numbered from 0)
	 * @param maxResults the maximum number of result objects to retrieve (or <=0 for no limit)
	 * @param sortProperty the property of the object to sort on
	 * @param isAscending should the retruned list be sorted ascending? 
	 * 
	 * @return a sorted List containing 0 or more Subclass objects.
	 *
	 * @see #listPage(int, int, String, boolean)
	 */
	List<Subclass> listPageByExample(final SubclassExample example,
			final int firstResult, final int maxResults,
			final String sortProperty, final boolean isAscending);

	/**
	 * Counts the number of persisted Subclass objects in the database.
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count();

	/**
	 * Counts the number of persisted Subclass objects in the database that
	 * matches the given example object.
	 *
	 * @param example
	 *                the example object to be counted
	 * 
	 * @return the number of persisted objects in the database.
	 */
	long count(final SubclassExample example);

	/**
	 * Selects Subclasss from the database that matches an
	 * example object using Query-by-Example(QBE).
	 * 
	 * @param example
	 *                the example object to which the result objects need to conform
	 * @return a List of Subclass objects.
	 */
	List<Subclass> findByExample(SubclassExample example);
}
