
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:42 CEST 2010
 *     Application model: Address
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Address extends AddressImplBase {

	/**
	 * Default no-argument constructor for Address 
	 */
	protected Address() {

	}

	/**
	 * Minimal constructor for Address
	 * @param streetName (String) 
	 * @param houseNumber (String) 
	 * @param zipcode (String) 
	 * @param city (String) 
	 */
	public Address(String streetName, String houseNumber, String zipcode,
			String city) {
		super(streetName, houseNumber, zipcode, city);
	}

}
