
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:36 CEST 2010
 *     Application model: CasusOverleg
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain;

import org.joda.time.DateTime;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class CasusOverleg extends CasusOverlegImplBase {

	/**
	 * Default no-argument constructor for CasusOverleg 
	 */
	protected CasusOverleg() {

	}

	/**
	 * Minimal constructor for CasusOverleg
	 * @param naam (String) 
	 * @param datum (DateTime) 
	 */
	public CasusOverleg(String naam, DateTime datum) {
		super(naam, datum);
	}

}
