
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:37 CEST 2010
 *     Application model: Empty2
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Empty2 extends Empty2ImplBase {

	/**
	 * Minimal constructor for Empty2
	 */
	public Empty2(

	) {
		super();
	}

}
