
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:33 CEST 2010
 *     Application model: Many2ManyTo
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain;

/**
 * This class has no meaning in the recordshop application. Its purpose is to test
uni-directional many-to-many associations
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Many2ManyTo extends Many2ManyToImplBase {

	/**
	 * Default no-argument constructor for Many2ManyTo 
	 */
	protected Many2ManyTo() {

	}

	/**
	 * Minimal constructor for Many2ManyTo
	 * @param property (String) 
	 */
	public Many2ManyTo(String property) {
		super(property);
	}

}
