
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:36 CEST 2010
 *     Application model: Subclass
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Subclass extends SubclassImplBase {

	/**
	 * Default no-argument constructor for Subclass 
	 */
	protected Subclass() {
		super();
	}

	/**
	 * Minimal constructor for Subclass
	 * @param name (String) 
	 */
	public Subclass(String name) {
		super(name);
	}

}
