
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:36 CEST 2010
 *     Application model: Superclass
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Superclass extends SuperclassImplBase {

	/**
	 * Default no-argument constructor for Superclass 
	 */
	protected Superclass() {

	}

	/**
	 * Minimal constructor for Superclass
	 * @param name (String) 
	 */
	public Superclass(String name) {
		super(name);
	}

}
