
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:42 CEST 2010
 *     Application model: Relation
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.domain;

import org.joda.time.DateTime;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Relation extends RelationImplBase {

	/**
	 * Default no-argument constructor for Relation 
	 */
	protected Relation() {

	}

	/**
	 * Minimal constructor for Relation
	 * @param name (String) 
	 */
	public Relation(String name) {
		super(name);
	}

}
