/**
 * Initially generated by Mod4j at Thu Feb 26 16:47:50 CET 2009
 */
package org.company.recordshop.data.hibernate.spring;

import org.company.recordshop.data.CustomerDao;

/**
 * Customer Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting Customer objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class CustomerDaoImpl extends CustomerDaoImplBase implements CustomerDao {

}
