
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Wed Oct 21 19:35:57 CEST 2009
 *     Application model: MyDerived
 *     Generator        :  Mod4j BusinessDomainDsl generator: DaoImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j.
 */

package org.company.recordshop.data.hibernate.spring;

import org.company.recordshop.data.MyDerivedDao;

/**
 * MyDerived Data Access Object (DOA) Implementation. Responsible for Creating,
 * Reading, Updating and Deleting MyDerived objects in the database. All database
 * access is done here.
 *  
 * @author Initially generated by Mod4j
 */
public class MyDerivedDaoImpl extends MyDerivedDaoImplBase
		implements
			MyDerivedDao {

}
