
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:08 CEST 2011
 *     Application model: AnotherRule
 *     Generator        : Mod4j BusinessDomainDsl genrator: NewBusinessRules.xpt
 */

package org.company.recordshop.domain.businessrules;

import org.company.recordshop.domain.Customer;
import org.springframework.validation.Validator;

/**
 * Just another rule
 *
 * @author Generated by Mod4j
 */
public abstract class AnotherRuleImplBase implements Validator {

	/**
	 * {@inheritDoc}
	 */
	public boolean supports(@SuppressWarnings("rawtypes") Class clazz) {
		return Customer.class.isAssignableFrom(clazz);
	}
}
