
/**
 * DO NOT MODIFY THIS FILE, CHANGES WILL BE AUTOMATICALLY OVERWRITTEN! 
 *
 * Generated by Mod4j. 
 *     Time             : Fri Jun 10 13:47:08 CEST 2011
 *     Application model: CheckProductMinimumQuantity
 *     Generator        : Mod4j BusinessDomainDsl genrator: NewBusinessRules.xpt
 */

package org.company.recordshop.domain.businessrules;

import org.company.recordshop.domain.OrderLine;
import org.springframework.validation.Validator;

/**
 * 
 *
 * @author Generated by Mod4j
 */
public abstract class CheckProductMinimumQuantityImplBase implements Validator {

	/**
	 * {@inheritDoc}
	 */
	public boolean supports(@SuppressWarnings("rawtypes") Class clazz) {
		return OrderLine.class.isAssignableFrom(clazz);
	}
}
