/**
 * Generated by Mod4j Service DSL: BusinessServiceImpl::BusinessServiceImpl at: Tue Feb 10 13:56:26 CET 2009
 * from model CustomerServiceModel
 */
package org.company.recordshop.business;


/**
 * @author Generated by Mod4j, use as extension point to implement custom business services
 */
public class CustomerServiceModelDomainServiceImpl
		extends
			CustomerServiceModelDomainServiceImplBase
		implements
			CustomerServiceModelDomainService {

}
