/**
 * Generated by Mod4j Service DSL: BusinessService::BusinessService at: Tue Feb 10 13:56:26 CET 2009
 * from model CustomerServiceModel
 */
package org.company.recordshop.business;

/**
 * @author Generated by Mod4j
 */
public interface CustomerServiceModelDomainService
		extends
			CustomerServiceModelDomainServiceBase {

}
