
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat May 15 10:32:38 CEST 2010
 *     Application model: Records
 *     Generator        :  Mod4j ServiceDsl generator: BusinessServiceImpl.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.business;

import org.company.recordshop.domain.Record;
import org.company.recordshop.data.RecordDao;

/**
 * @author Generated by Mod4j, use as extension point to implement custom business services
 */
public class RecordsDomainServiceImpl extends RecordsDomainServiceImplBase
		implements
			RecordsDomainService {

}
